# Generated by Django 4.1 on 2022-11-08 04:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('d927f1e8-5b8c-418d-a052-204b186d8fd0'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('task', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('isdone', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
