# Generated by Django 4.1 on 2022-12-05 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_todo_uid_timingtodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c7e98e79-72e4-463b-aa55-050e299a9c90'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c7e98e79-72e4-463b-aa55-050e299a9c90'), editable=False, primary_key=True, serialize=False),
        ),
    ]
