# Generated by Django 4.1 on 2022-12-05 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5fb65fe2-d399-4e56-aad8-292ed8814cdd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5fb65fe2-d399-4e56-aad8-292ed8814cdd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
