# Generated by Django 4.1 on 2022-12-14 04:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bd7d4d2a-023a-4f61-9570-dae84f05afda'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('bd7d4d2a-023a-4f61-9570-dae84f05afda'), editable=False, primary_key=True, serialize=False),
        ),
    ]
