# Generated by Django 4.1 on 2022-12-14 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7cd77a83-8375-49fa-bc2c-b682573bf933'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7cd77a83-8375-49fa-bc2c-b682573bf933'), editable=False, primary_key=True, serialize=False),
        ),
    ]
