# Generated by Django 4.1 on 2022-12-14 04:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8b33c2a6-8062-4ca4-8815-41898b2fd986'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('8b33c2a6-8062-4ca4-8815-41898b2fd986'), editable=False, primary_key=True, serialize=False),
        ),
    ]
