# Generated by Django 4.1 on 2022-12-14 04:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_timingtodo_uid_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('286ffeec-920e-4341-925e-e329cf77bd07'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('286ffeec-920e-4341-925e-e329cf77bd07'), editable=False, primary_key=True, serialize=False),
        ),
    ]
